# Generated by Django 3.2.9 on 2021-12-15 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_words_oz'),
        ('users', '0002_usernewword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernewword',
            name='new',
        ),
        migrations.RemoveField(
            model_name='usernewword',
            name='saved',
        ),
        migrations.AddField(
            model_name='usernewword',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-12-15 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernewword',
            name='words',
            field=models.ManyToManyField(to='data.Words', verbose_name='Yodlangan so`zlar'),
        ),
        migrations.CreateModel(
            name='DayWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(to='data.Words', verbose_name="Kunlik so'zlar")),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dayword')),
            ],
        ),
    ]
