# Generated by Django 3.2.9 on 2021-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211215_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayword',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernewword',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
