# Generated by Django 3.2.9 on 2021-12-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_words_oz'),
        ('users', '0005_alter_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='words',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.dayword'),
        ),
        migrations.AlterField(
            model_name='dayword',
            name='words',
            field=models.ManyToManyField(null=True, to='data.Words', verbose_name="Kunlik so'zlar"),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('customer', '1'), ('driver', '2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usernewword',
            name='words',
            field=models.ManyToManyField(null=True, to='data.Words', verbose_name='Yodlangan so`zlar'),
        ),
    ]
