# Generated by Django 3.2.9 on 2021-12-17 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='dayword',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usernewword',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
