# Generated by Django 3.2.9 on 2021-12-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211217_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayword',
            name='words_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
