# Generated by Django 3.2.9 on 2021-12-15 07:42

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_textdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdata',
            name='file',
            field=models.FileField(upload_to='static/uploads/', validators=[data.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='words',
            name='en',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ingliz'),
        ),
        migrations.AlterField(
            model_name='words',
            name='oz',
            field=models.CharField(max_length=255, unique=True, verbose_name="O'zbek"),
        ),
    ]
