# Generated by Django 3.2.9 on 2021-12-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_words_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='oz',
            field=models.CharField(max_length=255, verbose_name="O'zbek"),
        ),
    ]
